import type { Metadata } from "next";
import "./globals.css";
import { Baloo_Bhai_2 } from "next/font/google";
import Navbar from "@/component/Navbar";

const balooBhai = Baloo_Bhai_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // Baloo Bhai 2 supports these
  variable: "--font-baloo-bhai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={balooBhai.variable}>
        <header className="h-[6vh] lg:h-[10vh]">
          <Navbar />
        </header>
        <main className="flex flex-2">{children}</main>
        <footer className="bg-black h-[8vh] fixed bottom-0"></footer>
      </body>
    </html>
  );
}
