import type { Metadata } from "next";
import "./globals.css";
import { Baloo_Bhai_2 } from "next/font/google";
import { Toaster } from "react-hot-toast";
import LayoutWrapper from "@/component/LayoutWrapper";
import QueryProvider from "@/providers/QueryProvider";
import Script from "next/script";

const balooBhai = Baloo_Bhai_2({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"], // Baloo Bhai 2 supports these
  variable: "--font-baloo-bhai",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${balooBhai.variable} bg-linear-to-br from-white via-green-50 to-green-200 min-h-screen grid grid-rows-[auto_1fr]`}
      >
        <Toaster position="top-center" reverseOrder={false} />
        <QueryProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </QueryProvider>
      </body>
      <Script src="https://checkout.razorpay.com/v1/checkout.js" />
    </html>
  );
}
